# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emss0723.ui'
#
# Created: Tue Jul 23 17:24:19 2019
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 861)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1061, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(30, 530, 281, 141))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap(":/aaa/resource/logo.jpg"))
        self.label_44.setObjectName("label_44")
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_project_name.setGeometry(QtCore.QRect(370, 70, 441, 21))
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(290, 70, 72, 15))
        self.label_45.setObjectName("label_45")
        self.textEdit_describe = QtWidgets.QTextEdit(self.tab)
        self.textEdit_describe.setGeometry(QtCore.QRect(380, 130, 431, 87))
        self.textEdit_describe.setObjectName("textEdit_describe")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(290, 160, 72, 15))
        self.label_46.setObjectName("label_46")
        self.dateEdit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(830, 610, 191, 22))
        self.dateEdit.setDate(QtCore.QDate(2019, 6, 13))
        self.dateEdit.setObjectName("dateEdit")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(750, 610, 72, 15))
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(290, 250, 72, 15))
        self.label_50.setObjectName("label_50")
        self.lineEdit_designer_name = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_designer_name.setGeometry(QtCore.QRect(380, 250, 171, 21))
        self.lineEdit_designer_name.setObjectName("lineEdit_designer_name")
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setGeometry(QtCore.QRect(290, 310, 72, 15))
        self.label_51.setObjectName("label_51")
        self.lineEdit_design_department = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_design_department.setGeometry(QtCore.QRect(380, 300, 281, 21))
        self.lineEdit_design_department.setObjectName("lineEdit_design_department")
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(290, 360, 72, 15))
        self.label_52.setObjectName("label_52")
        self.lineEdit_design_company = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_design_company.setGeometry(QtCore.QRect(380, 360, 281, 21))
        self.lineEdit_design_company.setObjectName("lineEdit_design_company")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 501, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 236, 130))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_39)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(320, 20, 160, 63))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_44)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_45)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(300, 110, 72, 15))
        self.label_16.setObjectName("label_16")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(380, 110, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 40, 521, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(180, 30, 72, 15))
        self.label_40.setObjectName("label_40")
        self.lineEdit_tds_in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_tds_in.setGeometry(QtCore.QRect(260, 30, 113, 21))
        self.lineEdit_tds_in.setObjectName("lineEdit_tds_in")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 70, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(390, 30, 51, 20))
        self.label_13.setObjectName("label_13")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 120, 151, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(200, 120, 151, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(380, 400, 351, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 291, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.lineEdit_no3_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_no3_eq.setObjectName("lineEdit_no3_eq")
        self.gridLayout.addWidget(self.lineEdit_no3_eq, 5, 2, 1, 1)
        self.lineEdit_f = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_f.setObjectName("lineEdit_f")
        self.gridLayout.addWidget(self.lineEdit_f, 3, 1, 1, 1)
        self.lineEdit_so4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_so4.setObjectName("lineEdit_so4")
        self.gridLayout.addWidget(self.lineEdit_so4, 2, 1, 1, 1)
        self.lineEdit_po4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_po4.setObjectName("lineEdit_po4")
        self.gridLayout.addWidget(self.lineEdit_po4, 6, 1, 1, 1)
        self.lineEdit_hco3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_hco3.setObjectName("lineEdit_hco3")
        self.gridLayout.addWidget(self.lineEdit_hco3, 4, 1, 1, 1)
        self.lineEdit_cl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cl.setObjectName("lineEdit_cl")
        self.gridLayout.addWidget(self.lineEdit_cl, 1, 1, 1, 1)
        self.lineEdit_no3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_no3.setObjectName("lineEdit_no3")
        self.gridLayout.addWidget(self.lineEdit_no3, 5, 1, 1, 1)
        self.lineEdit_po4_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_po4_eq.setObjectName("lineEdit_po4_eq")
        self.gridLayout.addWidget(self.lineEdit_po4_eq, 6, 2, 1, 1)
        self.lineEdit_f_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_f_eq.setObjectName("lineEdit_f_eq")
        self.gridLayout.addWidget(self.lineEdit_f_eq, 3, 2, 1, 1)
        self.lineEdit_cl_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cl_eq.setObjectName("lineEdit_cl_eq")
        self.gridLayout.addWidget(self.lineEdit_cl_eq, 1, 2, 1, 1)
        self.lineEdit_so4_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_so4_eq.setObjectName("lineEdit_so4_eq")
        self.gridLayout.addWidget(self.lineEdit_so4_eq, 2, 2, 1, 1)
        self.lineEdit_hco3_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_hco3_eq.setObjectName("lineEdit_hco3_eq")
        self.gridLayout.addWidget(self.lineEdit_hco3_eq, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 400, 351, 281))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 46, 295, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_ba = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_ba.setObjectName("lineEdit_ba")
        self.gridLayout_3.addWidget(self.lineEdit_ba, 7, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_mg = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_mg.setObjectName("lineEdit_mg")
        self.gridLayout_3.addWidget(self.lineEdit_mg, 3, 1, 1, 1)
        self.lineEdit_fe_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_fe_eq.setObjectName("lineEdit_fe_eq")
        self.gridLayout_3.addWidget(self.lineEdit_fe_eq, 6, 2, 1, 1)
        self.lineEdit_mg_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_mg_eq.setObjectName("lineEdit_mg_eq")
        self.gridLayout_3.addWidget(self.lineEdit_mg_eq, 3, 2, 1, 1)
        self.lineEdit_nnh3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_nnh3.setObjectName("lineEdit_nnh3")
        self.gridLayout_3.addWidget(self.lineEdit_nnh3, 5, 1, 1, 1)
        self.lineEdit_ca = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_ca.setObjectName("lineEdit_ca")
        self.gridLayout_3.addWidget(self.lineEdit_ca, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)
        self.lineEdit_fe = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_fe.setObjectName("lineEdit_fe")
        self.gridLayout_3.addWidget(self.lineEdit_fe, 6, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 6, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 0, 1, 1)
        self.lineEdit_nnh3_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_nnh3_eq.setObjectName("lineEdit_nnh3_eq")
        self.gridLayout_3.addWidget(self.lineEdit_nnh3_eq, 5, 2, 1, 1)
        self.lineEdit_k = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.gridLayout_3.addWidget(self.lineEdit_k, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.lineEdit_na = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_na.setInputMask("")
        self.lineEdit_na.setObjectName("lineEdit_na")
        self.gridLayout_3.addWidget(self.lineEdit_na, 1, 1, 1, 1)
        self.lineEdit_ca_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_ca_eq.setObjectName("lineEdit_ca_eq")
        self.gridLayout_3.addWidget(self.lineEdit_ca_eq, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 1, 1, 1)
        self.lineEdit_na_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_na_eq.setObjectName("lineEdit_na_eq")
        self.gridLayout_3.addWidget(self.lineEdit_na_eq, 1, 2, 1, 1)
        self.lineEdit_k_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_k_eq.setObjectName("lineEdit_k_eq")
        self.gridLayout_3.addWidget(self.lineEdit_k_eq, 4, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 7, 0, 1, 1)
        self.lineEdit_ba_eq = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_ba_eq.setObjectName("lineEdit_ba_eq")
        self.gridLayout_3.addWidget(self.lineEdit_ba_eq, 7, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(750, 400, 291, 271))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 289, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 255, 135))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 0, 0, 1, 1)
        self.lineEdit_tds_o = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_tds_o.setObjectName("lineEdit_tds_o")
        self.gridLayout_2.addWidget(self.lineEdit_tds_o, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 1, 0, 1, 1)
        self.lineEdit_cation_o = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_cation_o.setObjectName("lineEdit_cation_o")
        self.gridLayout_2.addWidget(self.lineEdit_cation_o, 1, 2, 1, 1)
        self.lineEdit_anion_o = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_anion_o.setObjectName("lineEdit_anion_o")
        self.gridLayout_2.addWidget(self.lineEdit_anion_o, 2, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 3, 0, 1, 1)
        self.lineEdit_cation_eq = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_cation_eq.setObjectName("lineEdit_cation_eq")
        self.gridLayout_2.addWidget(self.lineEdit_cation_eq, 3, 2, 1, 1)
        self.lineEdit_anion_eq = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_anion_eq.setObjectName("lineEdit_anion_eq")
        self.gridLayout_2.addWidget(self.lineEdit_anion_eq, 4, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 3, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(60, 20, 161, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 210, 131, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 210, 131, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 240, 131, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setGeometry(QtCore.QRect(150, 240, 131, 28))
        self.pushButton_14.setObjectName("pushButton_14")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(410, 650, 72, 15))
        self.label_43.setObjectName("label_43")
        self.lineEdit_sio2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_sio2.setGeometry(QtCore.QRect(500, 650, 211, 21))
        self.lineEdit_sio2.setObjectName("lineEdit_sio2")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(50, 330, 891, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 70, 831, 611))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(480, 35, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 100, 93, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(340, 160, 191, 151))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 120, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(140, 0, 891, 661))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap(":/aaa/resource/RO_pic.jpg"))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 110, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 150, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 190, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 230, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_6, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 740, 201, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/aaa/resource/emem_logo2.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 760, 621, 20))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionClose)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.lineEdit_na.textChanged['QString'].connect(self.lineEdit_na_eq.setText)
        self.lineEdit_ca.textChanged['QString'].connect(self.lineEdit_ca_eq.setText)
        self.lineEdit_mg.textChanged['QString'].connect(self.lineEdit_mg_eq.setText)
        self.lineEdit_k.textChanged['QString'].connect(self.lineEdit_k_eq.setText)
        self.lineEdit_nnh3.textChanged['QString'].connect(self.lineEdit_nnh3_eq.setText)
        self.lineEdit_fe.textChanged['QString'].connect(self.lineEdit_fe_eq.setText)
        self.lineEdit_ba.textChanged['QString'].connect(self.lineEdit_ba_eq.setText)
        self.radioButton.clicked['bool'].connect(self.groupBox_6.setDisabled)
        self.radioButton.clicked['bool'].connect(self.groupBox_5.setDisabled)
        self.lineEdit_cl.textChanged['QString'].connect(self.lineEdit_cl_eq.setText)
        self.lineEdit_so4.textChanged['QString'].connect(self.lineEdit_so4_eq.setText)
        self.lineEdit_f.textChanged['QString'].connect(self.lineEdit_f_eq.setText)
        self.lineEdit_hco3.textChanged['QString'].connect(self.lineEdit_hco3_eq.setText)
        self.lineEdit_no3.textEdited['QString'].connect(self.lineEdit_no3_eq.setText)
        self.lineEdit_po4.textEdited['QString'].connect(self.lineEdit_po4_eq.setText)
        self.lineEdit_na.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_ca.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_mg.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_k.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_nnh3.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_fe.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_ba.textChanged['QString'].connect(self.lineEdit_cation_o.setText)
        self.lineEdit_cl.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_cl.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_f.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_hco3.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_no3.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_po4.textChanged['QString'].connect(self.lineEdit_anion_o.setText)
        self.lineEdit_cation_o.textChanged['QString'].connect(self.lineEdit_tds_o.setText)
        self.lineEdit_anion_o.textChanged['QString'].connect(self.lineEdit_tds_o.setText)
        self.lineEdit_na_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_ca_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_mg_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_k_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_k_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_nnh3_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_fe_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_ba_eq.textChanged['QString'].connect(self.lineEdit_cation_eq.setText)
        self.lineEdit_cl_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        self.lineEdit_so4_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        self.lineEdit_f_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        self.lineEdit_hco3_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        self.lineEdit_no3_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        self.lineEdit_po4_eq.textChanged['QString'].connect(self.lineEdit_anion_eq.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_project_name.setText(_translate("MainWindow", "*****设计计算"))
        self.label_45.setText(_translate("MainWindow", "项目名称："))
        self.textEdit_describe.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "描述信息："))
        self.label_47.setText(_translate("MainWindow", "日期"))
        self.label_50.setText(_translate("MainWindow", "设计人员："))
        self.lineEdit_designer_name.setText(_translate("MainWindow", "汪勇"))
        self.label_51.setText(_translate("MainWindow", "设计部门："))
        self.lineEdit_design_department.setText(_translate("MainWindow", "工业事业部"))
        self.label_52.setText(_translate("MainWindow", "设计单位："))
        self.lineEdit_design_company.setText(_translate("MainWindow", "杭州天创环境科技股份有限公司"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "项目信息"))
        self.groupBox.setTitle(_translate("MainWindow", "水源输入"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">水源</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "超滤产水"))
        self.comboBox.setItemText(1, _translate("MainWindow", "RO产水"))
        self.comboBox.setItemText(2, _translate("MainWindow", "地表水"))
        self.comboBox.setItemText(3, _translate("MainWindow", "砂滤微滤产水"))
        self.comboBox.setItemText(4, _translate("MainWindow", "海水"))
        self.comboBox.setItemText(5, _translate("MainWindow", "生化沉淀出水"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">给水水流 </span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">当前水流 </span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">占比%         </span></p></body></html>"))
        self.lineEdit_39.setText(_translate("MainWindow", "100"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">温度℃</span></p></body></html>"))
        self.lineEdit_44.setText(_translate("MainWindow", "25"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">pH</span></p></body></html>"))
        self.lineEdit_45.setText(_translate("MainWindow", "7"))
        self.label_16.setText(_translate("MainWindow", "回收率%"))
        self.lineEdit_8.setText(_translate("MainWindow", "50"))
        self.groupBox_2.setTitle(_translate("MainWindow", "快速设计计算"))
        self.label_40.setText(_translate("MainWindow", "以TDS计"))
        self.pushButton_5.setText(_translate("MainWindow", "氯化钠快速计算"))
        self.pushButton_6.setText(_translate("MainWindow", "硫酸钠快速计算"))
        self.label_13.setText(_translate("MainWindow", "mg/l"))
        self.pushButton_12.setText(_translate("MainWindow", "硫酸铵快速计算"))
        self.pushButton_13.setText(_translate("MainWindow", "氯化铵快速计算"))
        self.radioButton.setText(_translate("MainWindow", "快速输入"))
        self.groupBox_5.setTitle(_translate("MainWindow", "阴离子"))
        self.label_3.setText(_translate("MainWindow", "符号"))
        self.label_6.setText(_translate("MainWindow", "氟离子"))
        self.label_4.setText(_translate("MainWindow", "氯离子"))
        self.label_5.setText(_translate("MainWindow", "硫酸根"))
        self.label_8.setText(_translate("MainWindow", "硝酸根"))
        self.label_7.setText(_translate("MainWindow", "碳酸氢根"))
        self.label_9.setText(_translate("MainWindow", "磷酸根"))
        self.lineEdit_no3_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_f.setText(_translate("MainWindow", "0"))
        self.lineEdit_so4.setText(_translate("MainWindow", "0"))
        self.lineEdit_po4.setText(_translate("MainWindow", "0"))
        self.lineEdit_hco3.setText(_translate("MainWindow", "0"))
        self.lineEdit_cl.setText(_translate("MainWindow", "0"))
        self.lineEdit_no3.setText(_translate("MainWindow", "0"))
        self.lineEdit_po4_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_f_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_cl_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_so4_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_hco3_eq.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "mg/l"))
        self.label_11.setText(_translate("MainWindow", "meq/l"))
        self.groupBox_6.setTitle(_translate("MainWindow", "阳离子"))
        self.lineEdit_ba.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "钠离子"))
        self.lineEdit_mg.setText(_translate("MainWindow", "0"))
        self.lineEdit_fe_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_mg_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_nnh3.setText(_translate("MainWindow", "0"))
        self.lineEdit_ca.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "符号"))
        self.label_22.setText(_translate("MainWindow", "镁离子"))
        self.label_26.setText(_translate("MainWindow", "钾离子"))
        self.lineEdit_fe.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "铁离子"))
        self.label_25.setText(_translate("MainWindow", "氨氮离子"))
        self.lineEdit_nnh3_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_k.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "钙离子"))
        self.lineEdit_na.setText(_translate("MainWindow", "0"))
        self.lineEdit_ca_eq.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "mg/l"))
        self.lineEdit_na_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_k_eq.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "钡离子"))
        self.lineEdit_ba_eq.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "meq/l"))
        self.label_37.setText(_translate("MainWindow", "总阴离子"))
        self.label_35.setText(_translate("MainWindow", "TDS"))
        self.lineEdit_tds_o.setText(_translate("MainWindow", "0"))
        self.label_36.setText(_translate("MainWindow", "总阳离子"))
        self.lineEdit_cation_o.setText(_translate("MainWindow", "0"))
        self.lineEdit_anion_o.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "阳离子当量"))
        self.lineEdit_cation_eq.setText(_translate("MainWindow", "0"))
        self.lineEdit_anion_eq.setText(_translate("MainWindow", "0"))
        self.label_42.setText(_translate("MainWindow", "阴离子当量"))
        self.label_18.setText(_translate("MainWindow", "mg/l"))
        self.label_19.setText(_translate("MainWindow", "mg/l"))
        self.label_20.setText(_translate("MainWindow", "mg/l"))
        self.label_48.setText(_translate("MainWindow", "mg/l"))
        self.label_49.setText(_translate("MainWindow", "mg/l"))
        self.label_12.setText(_translate("MainWindow", "输出平衡"))
        self.pushButton_8.setText(_translate("MainWindow", "用钠离子平衡"))
        self.pushButton.setText(_translate("MainWindow", "用氯离子平衡"))
        self.pushButton_2.setText(_translate("MainWindow", "用硫酸根平衡"))
        self.pushButton_14.setText(_translate("MainWindow", "用氨离子平衡"))
        self.label_43.setText(_translate("MainWindow", "二氧化硅"))
        self.lineEdit_sio2.setText(_translate("MainWindow", "0"))
        self.label_17.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#5500ff;\">离子输入及平衡</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "水质水量"))
        self.label_14.setText(_translate("MainWindow", "结垢结果分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "结垢计算"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "膜设计"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "输出报告"))
        self.pushButton_3.setText(_translate("MainWindow", "换热计算"))
        self.pushButton_4.setText(_translate("MainWindow", "调节ph计算"))
        self.pushButton_7.setText(_translate("MainWindow", "软化计算"))
        self.pushButton_9.setText(_translate("MainWindow", "MVR计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "小工具"))
        self.label_2.setText(_translate("MainWindow", "Copyright © 2008-2012 杭州易膜环保科技有限公司  版权所有 All Rights Reserved "))
        self.menu.setTitle(_translate("MainWindow", "文件（&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Alt+O"))
        self.actionNew.setText(_translate("MainWindow", "new"))
        self.actionNew.setShortcut(_translate("MainWindow", "Alt+N"))
        self.actionClose.setText(_translate("MainWindow", "close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Alt+C"))

import image
