# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emss.ui'
#
# Created: Wed Jun 12 16:58:36 2019
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
import sys
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 861)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1081, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(30, 530, 281, 141))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap(":/aaa/resource/logo.jpg"))
        self.label_44.setObjectName("label_44")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_49.setGeometry(QtCore.QRect(370, 70, 441, 21))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(290, 70, 72, 15))
        self.label_45.setObjectName("label_45")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(380, 130, 431, 87))
        self.textEdit.setObjectName("textEdit")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(290, 160, 72, 15))
        self.label_46.setObjectName("label_46")
        self.dateEdit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(830, 610, 191, 22))
        self.dateEdit.setDate(QtCore.QDate(2019, 6, 13))
        self.dateEdit.setObjectName("dateEdit")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(750, 610, 72, 15))
        self.label_47.setObjectName("label_47")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 501, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 236, 130))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_39)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(320, 20, 160, 63))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_44)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_45)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 40, 521, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(330, 40, 131, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 80, 131, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(30, 130, 72, 15))
        self.label_40.setObjectName("label_40")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_43.setGeometry(QtCore.QRect(80, 130, 113, 21))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 30, 151, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 120, 131, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 400, 371, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 291, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 5, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 6, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 3, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 1, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 2, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 400, 351, 281))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 46, 295, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 7, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_3.addWidget(self.lineEdit_27, 3, 1, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_3.addWidget(self.lineEdit_33, 6, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_3.addWidget(self.lineEdit_34, 3, 2, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_3.addWidget(self.lineEdit_32, 5, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_3.addWidget(self.lineEdit_28, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_3.addWidget(self.lineEdit_29, 6, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 6, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_3.addWidget(self.lineEdit_26, 5, 2, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_3.addWidget(self.lineEdit_30, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_3.addWidget(self.lineEdit_31, 1, 1, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_3.addWidget(self.lineEdit_36, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 1, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_3.addWidget(self.lineEdit_35, 1, 2, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_3.addWidget(self.lineEdit_37, 4, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 7, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_3.addWidget(self.lineEdit_38, 7, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(800, 400, 221, 271))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 160, 135))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_40)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_41)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_42)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_46)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_47)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(390, 650, 72, 15))
        self.label_43.setObjectName("label_43")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_48.setGeometry(QtCore.QRect(470, 650, 211, 21))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 740, 201, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/aaa/resource/emem_logo2.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 760, 621, 20))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_45.setText(_translate("MainWindow", "项目名称"))
        self.label_46.setText(_translate("MainWindow", "描述"))
        self.label_47.setText(_translate("MainWindow", "日期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "项目信息"))
        self.groupBox.setTitle(_translate("MainWindow", "水源输入"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">水源</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">给水水流 </span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">当前水流 </span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">占比%         </span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">温度℃</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">pH</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "平衡条件"))
        self.pushButton.setText(_translate("MainWindow", "用氯离子平衡"))
        self.pushButton_2.setText(_translate("MainWindow", "用硫酸根平衡"))
        self.label_40.setText(_translate("MainWindow", "TDS"))
        self.pushButton_5.setText(_translate("MainWindow", "氯化钠快速计算"))
        self.pushButton_6.setText(_translate("MainWindow", "硫酸钠快速计算"))
        self.pushButton_8.setText(_translate("MainWindow", "用钠离子平衡"))
        self.groupBox_5.setTitle(_translate("MainWindow", "阴离子"))
        self.label_3.setText(_translate("MainWindow", "符号"))
        self.label_6.setText(_translate("MainWindow", "氟离子"))
        self.label_4.setText(_translate("MainWindow", "氯离子"))
        self.label_5.setText(_translate("MainWindow", "硫酸根"))
        self.label_8.setText(_translate("MainWindow", "硝酸根"))
        self.label_7.setText(_translate("MainWindow", "碳酸氢根"))
        self.label_9.setText(_translate("MainWindow", "磷酸根"))
        self.label_10.setText(_translate("MainWindow", "mg/l"))
        self.label_11.setText(_translate("MainWindow", "meq/l"))
        self.groupBox_6.setTitle(_translate("MainWindow", "阳离子"))
        self.label_23.setText(_translate("MainWindow", "钠离子"))
        self.label_21.setText(_translate("MainWindow", "符号"))
        self.label_22.setText(_translate("MainWindow", "离子"))
        self.label_26.setText(_translate("MainWindow", "离子"))
        self.label_27.setText(_translate("MainWindow", "铁离子"))
        self.label_25.setText(_translate("MainWindow", "氨氮离子"))
        self.label_24.setText(_translate("MainWindow", "离子"))
        self.label_28.setText(_translate("MainWindow", "mg/l"))
        self.label_30.setText(_translate("MainWindow", "钡离子"))
        self.label_29.setText(_translate("MainWindow", "meq/l"))
        self.label_35.setText(_translate("MainWindow", "TDS"))
        self.label_36.setText(_translate("MainWindow", "总阳离子"))
        self.label_37.setText(_translate("MainWindow", "总阴离子"))
        self.label_41.setText(_translate("MainWindow", "阳离子当量"))
        self.label_42.setText(_translate("MainWindow", "阴离子当量"))
        self.label_43.setText(_translate("MainWindow", "二氧化硅"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "水质水量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "结垢计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "膜配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "输出报告"))
        self.label_2.setText(_translate("MainWindow", "Copyright © 2008-2012 杭州易膜环保科技有限公司  版权所有 All Rights Reserved "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

import image

if __name__ == '__main__':
    myapp = QApplication(sys.argv)  #启动qt应用
    myDlg = QMainWindow()           #创建窗口类型实例
    myUI = Ui_MainWindow()          # 创建Ui界面的实例
    myUI.setupUi(myDlg)             #将ui界面实例装在进窗口
    myDlg.show()                    #展示窗口
    sys.exit(myapp.exec_())         #系统循环